sudo: false
language: node_js
node_js:
- 10.13.0
git:
  quiet: true
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  fqdn: loafofpiecrust.com
  target-branch: master
  on:
    branch: gatsby