backend:
  name: github
  repo: loafofpiecrust/loafofpiecrust.com
  branch: master
  site_domain: loafofpiecrust.com
  squash_merges: true

media_folder: static/media
public_folder: /media
display_url: https://loafofpiecrust.com

collections:
  # Project pages? Maybe these can be static rather than CMS-based?
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/content/projects
    create: true
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: externalUrl
        label: External URL
        required: false
      - name: body
        label: Description
        widget: markdown
    
  - name: blog
    label: Blog Posts
    label_singular: Post
    folder: src/content/blog
    create: true
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: date
        label: Publish Date
        widget: date
      - name: tags
        label: Tags
        widget: list
      - name: body
        label: Body
        widget: markdown
  
  # WIP: Story chapters linked in sequence
  - name: stories
    label: Stories
    label_singular: Story
    folder: src/content/stories
    create: true
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: date
        label: Publish Date
        widget: date
      - name: body
        label: Body
        widget: markdown