backend:
  name: github
  repo: loafofpiecrust/loafofpiecrust.github.io
  branch: gatsby
  squash_merges: true

media_folder: static/assets
public_folder: assets

collections:
  - name: "stories"
    label: "Stories"
    folder: "src/content/test/stories"
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: date
        label: Publish Date
        widget: date
      - name: body
        label: Body
        widget: markdown