backend:
  name: gitlab
  repo: loafofpiecrust/loafofpiecrust.com
  branch: master
  auth_type: implicit
  app_id: 676164035782addc07ffd3af42ec256b8206f502f1cf458dd577f318b462f338
  site_domain: loafofpiecrust.com
  squash_merges: true

media_folder: static/media
public_folder: /media
display_url: https://loafofpiecrust.com

collections:
  - name: stories
    label: Stories
    label_singular: Story
    folder: src/content/stories
    create: true
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: date
        label: Publish Date
        widget: date
      - name: body
        label: Body
        widget: markdown
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/content/projects
    create: true
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
      - name: externalUrl
        label: External URL
        required: false
      - name: body
        label: Description
        widget: markdown